Repository B00KJourney/bookJourney-backend, pull requests merged in 2025-02, with the labels that each got.

#91 [FEAT] 이메일 인증코드/확인 요청 구현
  build.gradle
  src/main/java/com/example/bookjourneybackend/domain/auth/controller/AuthController.java
  src/main/java/com/example/bookjourneybackend/domain/auth/service/AuthService.java
  src/main/java/com/example/bookjourneybackend/domain/auth/service/RedisService.java
  src/main/java/com/example/bookjourneybackend/domain/auth/service/TokenService.java
  src/main/java/com/example/bookjourneybackend/domain/record/service/RecordService.java
  src/main/java/com/example/bookjourneybackend/domain/user/controller/UserController.java
  src/main/java/com/example/bookjourneybackend/domain/user/domain/EmailContentTemplate.java
  src/main/java/com/example/bookjourneybackend/domain/user/domain/dto/request/PostUsersEmailRequest.java
  src/main/java/com/example/bookjourneybackend/domain/user/domain/dto/request/PostUsersVerificationEmailRequest.java
  src/main/java/com/example/bookjourneybackend/domain/user/domain/dto/response/PostUsersValidationResponse.java
  src/main/java/com/example/bookjourneybackend/domain/user/domain/repository/UserRepository.java
  src/main/java/com/example/bookjourneybackend/domain/user/service/MailService.java
  src/main/java/com/example/bookjourneybackend/domain/user/service/UserService.java
  src/main/java/com/example/bookjourneybackend/global/config/EmailConfig.java
  src/main/java/com/example/bookjourneybackend/global/response/status/BaseExceptionResponseStatus.java
  src/main/java/com/example/bookjourneybackend/global/util/DateUtil.java
  src/main/java/com/example/bookjourneybackend/global/util/JwtAuthenticationFilter.java
  src/main/resources/application.yml
Labels: 희진, 🛠️ feat, 🍀 refactor

#92 [FEAT] 기록 좋아요
  src/main/java/com/example/bookjourneybackend/domain/record/controller/RecordController.java
  src/main/java/com/example/bookjourneybackend/domain/record/domain/repository/RecordLikeRepository.java
  src/main/java/com/example/bookjourneybackend/domain/record/dto/response/PostRecordLikeResponse.java
  src/main/java/com/example/bookjourneybackend/domain/record/service/RecordService.java
  src/main/java/com/example/bookjourneybackend/domain/room/controller/RoomController.java
  src/main/java/com/example/bookjourneybackend/global/response/status/BaseExceptionResponseStatus.java
Labels: 나은, 🛠️ feat, 🍀 refactor

#95 [FEAT] swagger에서 authorize하기
  src/main/java/com/example/bookjourneybackend/global/config/SwaggerConfig.java
Labels: 나은, 🛠️ feat

#96 [FIX] 베스트셀러 DB 저장
  src/main/java/com/example/bookjourneybackend/domain/book/domain/repository/BookRepository.java
  src/main/java/com/example/bookjourneybackend/domain/book/service/BestSellerService.java
  src/main/java/com/example/bookjourneybackend/domain/book/service/BestsellerUpdateScheduler.java
  src/main/java/com/example/bookjourneybackend/domain/book/service/BookCacheService.java
  src/main/java/com/example/bookjourneybackend/domain/record/service/RecordService.java
  src/main/java/com/example/bookjourneybackend/domain/room/service/RoomService.java
  src/main/java/com/example/bookjourneybackend/domain/test/TestRequest.java
  src/main/java/com/example/bookjourneybackend/domain/user/service/UserService.java
  src/main/java/com/example/bookjourneybackend/domain/userRoom/domain/UserRole.java
  src/main/java/com/example/bookjourneybackend/global/response/status/BaseExceptionResponseStatus.java
  src/main/java/com/example/bookjourneybackend/global/util/AladinApiUtil.java
  src/main/java/com/example/bookjourneybackend/global/util/DateUtil.java
Labels: 희진, ⚡️ fix, 🍀 refactor

#98 [FEAT] 최근 검색어 조회 기능 구현
  src/main/java/com/example/bookjourneybackend/domain/recentSearch/controller/RecentSearchController.java
  src/main/java/com/example/bookjourneybackend/domain/recentSearch/domain/dto/response/GetRecentSearchResponse.java
  src/main/java/com/example/bookjourneybackend/domain/recentSearch/domain/dto/response/RecentSearchInfo.java
  src/main/java/com/example/bookjourneybackend/domain/recentSearch/domain/repository/RecentSearchRepository.java
  src/main/java/com/example/bookjourneybackend/domain/recentSearch/service/RecentSearchService.java
Labels: 희진, 🛠️ feat

#99 [FEAT] 최근검색어 삭제 기능 구현
  src/main/java/com/example/bookjourneybackend/domain/recentSearch/controller/RecentSearchController.java
  src/main/java/com/example/bookjourneybackend/domain/recentSearch/domain/repository/RecentSearchRepository.java
  src/main/java/com/example/bookjourneybackend/domain/recentSearch/service/RecentSearchService.java
  src/main/java/com/example/bookjourneybackend/global/response/status/BaseExceptionResponseStatus.java
Labels: 희진, 🛠️ feat

#100 [FEAT] 최근 검색어 모두 삭제 기능 구현
  src/main/java/com/example/bookjourneybackend/domain/recentSearch/controller/RecentSearchController.java
  src/main/java/com/example/bookjourneybackend/domain/recentSearch/domain/repository/RecentSearchRepository.java
  src/main/java/com/example/bookjourneybackend/domain/recentSearch/service/RecentSearchService.java
  src/main/java/com/example/bookjourneybackend/global/response/status/BaseExceptionResponseStatus.java
Labels: 희진, 🛠️ feat

#111 Refactor/#110 room search image
  src/main/java/com/example/bookjourneybackend/domain/room/dto/response/RoomInfo.java
  src/main/java/com/example/bookjourneybackend/domain/room/service/RoomService.java
Labels: 나은, 🍀 refactor

#106 [FEAT] 읽은 페이지 입력 시 페이지 조회
  src/main/java/com/example/bookjourneybackend/domain/room/controller/RoomController.java
  src/main/java/com/example/bookjourneybackend/domain/room/dto/response/GetRoomPagesResponse.java
  src/main/java/com/example/bookjourneybackend/domain/room/service/RoomService.java
Labels: 나은, 🛠️ feat

#105 [FEAT] 페이지 입력
  src/main/java/com/example/bookjourneybackend/domain/record/controller/RecordController.java
  src/main/java/com/example/bookjourneybackend/domain/record/dto/response/PostRecordPageResponse.java
  src/main/java/com/example/bookjourneybackend/domain/record/service/RecordService.java
  src/main/java/com/example/bookjourneybackend/domain/room/domain/Room.java
  src/main/java/com/example/bookjourneybackend/domain/userRoom/domain/UserRoom.java
  src/main/java/com/example/bookjourneybackend/domain/userRoom/domain/repository/UserRoomRepository.java
  src/main/java/com/example/bookjourneybackend/global/response/status/BaseExceptionResponseStatus.java
Labels: 나은, 🛠️ feat, ⚡️ fix

#113 [FEAT] 즐겨찾기 추가 기능 구현
  src/main/java/com/example/bookjourneybackend/domain/book/service/BookCacheService.java
  src/main/java/com/example/bookjourneybackend/domain/favorite/controller/FavoriteController.java
  src/main/java/com/example/bookjourneybackend/domain/favorite/domain/dto/response/PostFavoriteAddResponse.java
  src/main/java/com/example/bookjourneybackend/domain/favorite/domain/repository/FavoriteRepository.java
  src/main/java/com/example/bookjourneybackend/domain/favorite/service/FavoriteService.java
  src/main/java/com/example/bookjourneybackend/global/response/status/BaseExceptionResponseStatus.java
Labels: 희진, 🛠️ feat

#114 [FEAT] 독서기록장(다 안 읽었어요) 조회 api 구현
  src/main/java/com/example/bookjourneybackend/domain/room/controller/RoomArchiveController.java
  src/main/java/com/example/bookjourneybackend/domain/room/domain/Room.java
  src/main/java/com/example/bookjourneybackend/domain/room/dto/response/GetRoomArchiveResponse.java
  src/main/java/com/example/bookjourneybackend/domain/room/service/RoomArchiveService.java
  src/main/java/com/example/bookjourneybackend/domain/room/service/RoomService.java
  src/main/java/com/example/bookjourneybackend/domain/userRoom/domain/UserRoom.java
  src/main/java/com/example/bookjourneybackend/domain/userRoom/domain/repository/UserRoomRepository.java
  src/main/java/com/example/bookjourneybackend/global/util/DateUtil.java
Labels: 현준, 🛠️ feat

#116 [FEAT] 즐겨찾기 조회 기능 구현
  src/main/java/com/example/bookjourneybackend/domain/book/dto/response/BookInfo.java
  src/main/java/com/example/bookjourneybackend/domain/favorite/controller/FavoriteController.java
  src/main/java/com/example/bookjourneybackend/domain/favorite/domain/dto/response/GetFavoriteListResponse.java
  src/main/java/com/example/bookjourneybackend/domain/favorite/domain/repository/FavoriteRepository.java
  src/main/java/com/example/bookjourneybackend/domain/favorite/service/FavoriteService.java
Labels: 희진, 🛠️ feat

#118 [FEAT] 독서기록장 (다 읽었어요) api 구현
  src/main/java/com/example/bookjourneybackend/domain/room/controller/RoomArchiveController.java
  src/main/java/com/example/bookjourneybackend/domain/room/dto/request/PostRoomCreateRequest.java
  src/main/java/com/example/bookjourneybackend/domain/room/service/RoomArchiveService.java
  src/main/java/com/example/bookjourneybackend/domain/room/service/RoomService.java
  src/main/java/com/example/bookjourneybackend/domain/userRoom/domain/repository/UserRoomRepository.java
  src/main/java/com/example/bookjourneybackend/global/config/initData/RecentSearchInitializer.java
  src/main/java/com/example/bookjourneybackend/global/config/initData/UserRoomInitializer.java
  src/main/java/com/example/bookjourneybackend/global/response/status/BaseExceptionResponseStatus.java
Labels: 현준, 🛠️ feat

#120 [FIX]: 독서기록장 (다 읽었어요 dto 반환 수정)
  src/main/java/com/example/bookjourneybackend/domain/room/dto/response/RecordInfo.java
  src/main/java/com/example/bookjourneybackend/domain/room/service/RoomArchiveService.java
  src/main/java/com/example/bookjourneybackend/global/util/DateUtil.java
Labels: 현준, ⚡️ fix, 🍀 refactor

#123 [REFACTOR] 방 상세보기에서 책 정보도 나오게 수정
  src/main/java/com/example/bookjourneybackend/domain/room/dto/response/GetRoomDetailResponse.java
  src/main/java/com/example/bookjourneybackend/domain/room/service/RoomService.java
Labels: 나은, 🍀 refactor

#124 [FEAT] 댓글 조회
  src/main/java/com/example/bookjourneybackend/domain/comment/controller/CommentController.java
  src/main/java/com/example/bookjourneybackend/domain/comment/domain/Comment.java
  src/main/java/com/example/bookjourneybackend/domain/comment/domain/dto/response/CommentInfo.java
  src/main/java/com/example/bookjourneybackend/domain/comment/domain/dto/response/GetCommentListResponse.java
  src/main/java/com/example/bookjourneybackend/domain/comment/domain/repository/CommentLikeRepository.java
  src/main/java/com/example/bookjourneybackend/domain/comment/domain/repository/CommentRepository.java
  src/main/java/com/example/bookjourneybackend/domain/comment/service/CommentService.java
  src/main/java/com/example/bookjourneybackend/global/config/initData/CommentInitializer.java
Labels: 나은, 🛠️ feat, 🍀 refactor

#133 [REFACTOR] 댓글 정보 조회 시 기록 정보도 조회하게끔 수정
  src/main/java/com/example/bookjourneybackend/domain/comment/domain/dto/response/GetCommentListResponse.java
  src/main/java/com/example/bookjourneybackend/domain/comment/service/CommentService.java
Labels: 나은, 🍀 refactor

#125 [FEAT] 즐겨찾기 선택 삭제 구현
  src/main/java/com/example/bookjourneybackend/domain/auth/domain/dto/request/PostAuthAccessTokenReissueRequest.java
  src/main/java/com/example/bookjourneybackend/domain/favorite/controller/FavoriteController.java
  src/main/java/com/example/bookjourneybackend/domain/favorite/domain/dto/request/DeleteFavoriteSelectedRequest.java
  src/main/java/com/example/bookjourneybackend/domain/favorite/service/FavoriteService.java
  src/main/java/com/example/bookjourneybackend/global/response/status/BaseExceptionResponseStatus.java
Labels: 희진, 🛠️ feat

#129 [REFACTOR] 책/방 검색시 최근 검색어 추가
  src/main/java/com/example/bookjourneybackend/domain/book/controller/BookController.java
  src/main/java/com/example/bookjourneybackend/domain/book/service/BookService.java
  src/main/java/com/example/bookjourneybackend/domain/recentSearch/domain/repository/RecentSearchRepository.java
  src/main/java/com/example/bookjourneybackend/domain/recentSearch/service/RecentSearchService.java
  src/main/java/com/example/bookjourneybackend/domain/room/controller/RoomController.java
  src/main/java/com/example/bookjourneybackend/domain/room/service/RoomService.java
  src/main/java/com/example/bookjourneybackend/global/entity/BaseEntity.java
Labels: 현준, 🍀 refactor

#134 [FEAT] 댓글 작성
  src/main/java/com/example/bookjourneybackend/domain/comment/controller/CommentController.java
  src/main/java/com/example/bookjourneybackend/domain/comment/domain/dto/request/PostCommentRequest.java
  src/main/java/com/example/bookjourneybackend/domain/comment/domain/dto/response/PostCommentResponse.java
  src/main/java/com/example/bookjourneybackend/domain/comment/service/CommentService.java
  src/main/java/com/example/bookjourneybackend/domain/userRoom/domain/repository/UserRoomRepository.java
  src/main/java/com/example/bookjourneybackend/global/response/status/BaseExceptionResponseStatus.java
Labels: 나은, 🛠️ feat, 🍀 refactor

#135 [FEAT] 댓글 좋아요
  src/main/java/com/example/bookjourneybackend/domain/comment/controller/CommentController.java
  src/main/java/com/example/bookjourneybackend/domain/comment/domain/dto/response/PostCommentLikeResponse.java
  src/main/java/com/example/bookjourneybackend/domain/comment/domain/repository/CommentLikeRepository.java
  src/main/java/com/example/bookjourneybackend/domain/comment/service/CommentService.java
  src/main/java/com/example/bookjourneybackend/domain/record/domain/repository/RecordLikeRepository.java
  src/main/java/com/example/bookjourneybackend/domain/record/service/RecordService.java
  src/main/java/com/example/bookjourneybackend/global/response/status/BaseExceptionResponseStatus.java
Labels: 나은, 🛠️ feat, ⚡️ fix

#137 [CHORE] Spring AOP를 통한 Controller 호출전, 반환후 로깅 출력
  .github/workflows/cd-workflow.yml
  src/main/java/com/example/bookjourneybackend/domain/auth/controller/AuthController.java
  src/main/java/com/example/bookjourneybackend/domain/auth/service/AuthService.java
  src/main/java/com/example/bookjourneybackend/domain/auth/service/RedisService.java
  src/main/java/com/example/bookjourneybackend/domain/book/controller/BookController.java
  src/main/java/com/example/bookjourneybackend/domain/book/service/BestSellerService.java
  src/main/java/com/example/bookjourneybackend/domain/book/service/BestsellerUpdateScheduler.java
  src/main/java/com/example/bookjourneybackend/domain/book/service/BookCacheService.java
  src/main/java/com/example/bookjourneybackend/domain/book/service/BookService.java
  src/main/java/com/example/bookjourneybackend/domain/comment/controller/CommentController.java
  src/main/java/com/example/bookjourneybackend/domain/comment/service/CommentService.java
  src/main/java/com/example/bookjourneybackend/domain/favorite/controller/FavoriteController.java
  src/main/java/com/example/bookjourneybackend/domain/favorite/service/FavoriteService.java
  src/main/java/com/example/bookjourneybackend/domain/recentSearch/controller/RecentSearchController.java
  src/main/java/com/example/bookjourneybackend/domain/recentSearch/service/RecentSearchService.java
  src/main/java/com/example/bookjourneybackend/domain/record/controller/RecordController.java
  src/main/java/com/example/bookjourneybackend/domain/record/service/RecordService.java
  src/main/java/com/example/bookjourneybackend/domain/room/controller/RoomArchiveController.java
  src/main/java/com/example/bookjourneybackend/domain/room/controller/RoomController.java
  src/main/java/com/example/bookjourneybackend/domain/room/service/RoomArchiveService.java
  src/main/java/com/example/bookjourneybackend/domain/room/service/RoomService.java
  src/main/java/com/example/bookjourneybackend/domain/user/controller/UserController.java
  src/main/java/com/example/bookjourneybackend/domain/user/service/MailService.java
  src/main/java/com/example/bookjourneybackend/domain/user/service/UserService.java
  src/main/java/com/example/bookjourneybackend/global/logging/ControllerLoggingAspect.java
  src/main/java/com/example/bookjourneybackend/global/util/JwtAuthenticationFilter.java
Labels: 현준, 🧹 chore

#144 [FIX]: 베스트셀러 조회시 response dto nickname추가 수정
  src/main/java/com/example/bookjourneybackend/domain/book/dto/response/GetBookBestSellersResponse.java
  src/main/java/com/example/bookjourneybackend/domain/book/service/BookService.java
Labels: 희진, ⚡️ fix

#140 [FEAT] 즐겨찾기 삭제 구현
  src/main/java/com/example/bookjourneybackend/domain/book/service/BestSellerService.java
  src/main/java/com/example/bookjourneybackend/domain/book/service/BookService.java
  src/main/java/com/example/bookjourneybackend/domain/favorite/controller/FavoriteController.java
  src/main/java/com/example/bookjourneybackend/domain/favorite/domain/repository/FavoriteRepository.java
  src/main/java/com/example/bookjourneybackend/domain/favorite/service/FavoriteService.java
Labels: 희진, 🛠️ feat, 🍀 refactor

#154 [REFACTOR] DELETED 상태 없애기
  src/main/java/com/example/bookjourneybackend/domain/record/service/RecordService.java
  src/main/java/com/example/bookjourneybackend/domain/room/dto/response/GetRoomDetailResponse.java
  src/main/java/com/example/bookjourneybackend/domain/room/service/RoomService.java
  src/main/java/com/example/bookjourneybackend/domain/userRoom/domain/UserRoom.java
  src/main/java/com/example/bookjourneybackend/global/entity/EntityStatus.java
Labels: 나은, 🍀 refactor

#146 [FEAT] 검색 후 비공개방 진입 시
  src/main/java/com/example/bookjourneybackend/domain/room/controller/RoomController.java
  src/main/java/com/example/bookjourneybackend/domain/room/dto/response/GetSearchPrivateRoomResponse.java
  src/main/java/com/example/bookjourneybackend/domain/room/service/RoomService.java
  src/main/java/com/example/bookjourneybackend/global/response/status/BaseExceptionResponseStatus.java
Labels: 나은, 🛠️ feat

#157 [FEAT] 독서달력 조회용 api 구현
  src/main/java/com/example/bookjourneybackend/domain/record/service/RecordService.java
  src/main/java/com/example/bookjourneybackend/domain/user/controller/MyPageController.java
  src/main/java/com/example/bookjourneybackend/domain/user/dto/response/CalendarData.java
  src/main/java/com/example/bookjourneybackend/domain/user/dto/response/GetMyPageCalendarResponse.java
  src/main/java/com/example/bookjourneybackend/domain/user/service/MyPageService.java
  src/main/java/com/example/bookjourneybackend/domain/userRoom/domain/UserRoom.java
  src/main/java/com/example/bookjourneybackend/domain/userRoom/domain/repository/UserRoomRepository.java
Labels: 현준, 🛠️ feat

#161 [REFACTOR] DB에 실질적인 데이터 추가
  .github/workflows/cd-workflow.yml
  src/main/java/com/example/bookjourneybackend/domain/room/domain/Room.java
  src/main/java/com/example/bookjourneybackend/domain/userRoom/domain/UserRoom.java
  src/main/java/com/example/bookjourneybackend/global/config/initData/BookInitializer.java
  src/main/java/com/example/bookjourneybackend/global/config/initData/CommentInitializer.java
  src/main/java/com/example/bookjourneybackend/global/config/initData/CommentLikeInitializer.java
  src/main/java/com/example/bookjourneybackend/global/config/initData/DataLoader.java
  src/main/java/com/example/bookjourneybackend/global/config/initData/FavoriteGenreInitializer.java
  src/main/java/com/example/bookjourneybackend/global/config/initData/FavoriteInitializer.java
  src/main/java/com/example/bookjourneybackend/global/config/initData/RecentSearchInitializer.java
  src/main/java/com/example/bookjourneybackend/global/config/initData/RecordInitializer.java
  src/main/java/com/example/bookjourneybackend/global/config/initData/RecordLikeInitializer.java
  src/main/java/com/example/bookjourneybackend/global/config/initData/RoomInitializer.java
  src/main/java/com/example/bookjourneybackend/global/config/initData/UserInitializer.java
  src/main/java/com/example/bookjourneybackend/global/config/initData/UserRoomInitializer.java
Labels: 희진, 🍀 refactor

#158 [FEAT] 마이페이지 유저 정보
  src/main/java/com/example/bookjourneybackend/domain/user/controller/MyPageController.java
  src/main/java/com/example/bookjourneybackend/domain/user/dto/response/GetMyPageUserInfoResponse.java
  src/main/java/com/example/bookjourneybackend/domain/user/service/MyPageService.java
Labels: 나은, 🛠️ feat

#160 [FEAT] 독서달력 상세보기 api 구현
  src/main/java/com/example/bookjourneybackend/domain/user/controller/MyPageController.java
  src/main/java/com/example/bookjourneybackend/domain/user/dto/response/CalendarData.java
  src/main/java/com/example/bookjourneybackend/domain/user/service/MyPageService.java
  src/main/java/com/example/bookjourneybackend/domain/userRoom/domain/repository/UserRoomRepository.java
  src/main/java/com/example/bookjourneybackend/global/response/status/BaseExceptionResponseStatus.java
Labels: 현준, 🛠️ feat

#164 [FIX] application.yml 수정 및 검색 메서드 오류 해결
  .github/workflows/cd-workflow.yml
  build.gradle
  src/main/java/com/example/bookjourneybackend/domain/book/service/BookService.java
  src/main/java/com/example/bookjourneybackend/domain/room/service/RoomService.java
  src/main/java/com/example/bookjourneybackend/global/config/initData/DataLoader.java
  src/main/java/com/example/bookjourneybackend/global/util/AladinApiUtil.java
  src/main/resources/application.yml
Labels: 현준, ⚡️ fix

#165 [REFACTOR] 이미지 업로드 용량 제한 증가
  src/main/resources/application.yml
Labels: 현준, 🍀 refactor

#167 [FEAT] 스케줄러를 통해 자정마다 EXPIRED되는 Room을 탐색
  src/main/java/com/example/bookjourneybackend/domain/room/domain/repository/RoomRepository.java
  src/main/java/com/example/bookjourneybackend/domain/room/service/RoomService.java
  src/main/java/com/example/bookjourneybackend/global/scheduler/BestsellerUpdateScheduler.java
  src/main/java/com/example/bookjourneybackend/global/scheduler/CheckExpiredScheduler.java
  src/main/java/com/example/bookjourneybackend/global/util/DateUtil.java
Labels: 현준, 🛠️ feat

#170 [FEAT] 프로필 수정 기능 구현
  src/main/java/com/example/bookjourneybackend/domain/user/controller/MyPageController.java
  src/main/java/com/example/bookjourneybackend/domain/user/domain/User.java
  src/main/java/com/example/bookjourneybackend/domain/user/domain/repository/UserRepository.java
  src/main/java/com/example/bookjourneybackend/domain/user/dto/request/PatchUserInfoRequest.java
  src/main/java/com/example/bookjourneybackend/domain/user/dto/response/PatchUserInfoResponse.java
  src/main/java/com/example/bookjourneybackend/domain/user/service/MyPageService.java
Labels: 희진, 🛠️ feat

#176 [FIX] 독서기록장 api에 로그인된 사용자의 닉네임 반환 추가
  src/main/java/com/example/bookjourneybackend/domain/room/dto/response/GetRoomArchiveResponse.java
  src/main/java/com/example/bookjourneybackend/domain/room/service/RoomArchiveService.java
Labels: 현준, ⚡️ fix

#178 [REFACTOR] 방 정보에 recruitCount 추가
  src/main/java/com/example/bookjourneybackend/domain/room/dto/response/GetRoomInfoResponse.java
  src/main/java/com/example/bookjourneybackend/domain/room/service/RoomService.java
Labels: 나은, 🍀 refactor

#179 [FEAT] 비밀번호 변경
  src/main/java/com/example/bookjourneybackend/domain/user/controller/MyPageController.java
  src/main/java/com/example/bookjourneybackend/domain/user/domain/User.java
  src/main/java/com/example/bookjourneybackend/domain/user/dto/request/PatchUsersPasswordRequest.java
  src/main/java/com/example/bookjourneybackend/domain/user/service/MyPageService.java
  src/main/java/com/example/bookjourneybackend/global/response/BaseResponse.java
  src/main/java/com/example/bookjourneybackend/global/response/status/BaseExceptionResponseStatus.java
Labels: 나은, 🛠️ feat

#183 [REFACTOR] 독서기록장에서 닉네임 반환 대신 사용자의 회원가입 날짜 반환으로 수정
  src/main/java/com/example/bookjourneybackend/domain/room/dto/response/GetRoomArchiveResponse.java
  src/main/java/com/example/bookjourneybackend/domain/room/service/RoomArchiveService.java
  src/main/java/com/example/bookjourneybackend/global/util/DateUtil.java
Labels: 현준, ⚡️ fix, 🍀 refactor

#173 [REFACTOR] 책 검색 로직 오류 수정
  src/main/java/com/example/bookjourneybackend/domain/room/domain/repository/RoomRepository.java
  src/main/java/com/example/bookjourneybackend/domain/room/service/RoomService.java
Labels: 나은, ⚡️ fix, 🍀 refactor

#174 [FEAT] 책산책 칭호
  src/main/java/com/example/bookjourneybackend/domain/record/dto/response/PostRecordResponse.java
  src/main/java/com/example/bookjourneybackend/domain/record/service/RecordService.java
  src/main/java/com/example/bookjourneybackend/domain/user/controller/MyPageController.java
  src/main/java/com/example/bookjourneybackend/domain/user/domain/CollectorNicknameType.java
  src/main/java/com/example/bookjourneybackend/domain/user/domain/repository/UserRepository.java
  src/main/java/com/example/bookjourneybackend/domain/user/dto/response/GetMyPageCollectorNicknameResponse.java
  src/main/java/com/example/bookjourneybackend/domain/user/service/MyPageService.java
Labels: 나은, 🛠️ feat, 🍀 refactor

#184 [FEAT] 기록 삭제
  src/main/java/com/example/bookjourneybackend/domain/record/controller/RecordController.java
  src/main/java/com/example/bookjourneybackend/domain/record/domain/repository/RecordRepository.java
  src/main/java/com/example/bookjourneybackend/domain/record/service/RecordService.java
  src/main/java/com/example/bookjourneybackend/global/response/status/BaseExceptionResponseStatus.java
Labels: 나은, 🛠️ feat

#185 [FEAT] 회원 탈퇴
  src/main/java/com/example/bookjourneybackend/domain/user/controller/MyPageController.java
  src/main/java/com/example/bookjourneybackend/domain/user/domain/User.java
  src/main/java/com/example/bookjourneybackend/domain/user/service/MyPageService.java
Labels: 나은, 🛠️ feat

#186 [FEAT] 댓글 삭제
  src/main/java/com/example/bookjourneybackend/domain/comment/controller/CommentController.java
  src/main/java/com/example/bookjourneybackend/domain/comment/service/CommentService.java
  src/main/java/com/example/bookjourneybackend/global/response/status/BaseExceptionResponseStatus.java
Labels: 나은, 🛠️ feat

#191 [BUG] 책 찾기 api에서 각 책에 대한 정보를 캐싱할 때 장르 파싱 오류 수정
  src/main/java/com/example/bookjourneybackend/domain/book/domain/Book.java
  src/main/java/com/example/bookjourneybackend/domain/book/service/BookService.java
  src/main/java/com/example/bookjourneybackend/domain/comment/domain/Comment.java
  src/main/java/com/example/bookjourneybackend/domain/recentSearch/domain/RecentSearch.java
  src/main/java/com/example/bookjourneybackend/domain/record/domain/Record.java
  src/main/java/com/example/bookjourneybackend/domain/room/domain/Room.java
  src/main/java/com/example/bookjourneybackend/domain/user/domain/User.java
Labels: 현준, ⚡️ fix

#195 [REFACTOR] 읽기횟수가 많은 책 조회시 만료된 방도 추가
  src/main/java/com/example/bookjourneybackend/domain/book/domain/repository/BookRepository.java
  src/main/java/com/example/bookjourneybackend/domain/user/controller/MyPageController.java
  src/main/java/com/example/bookjourneybackend/domain/userRoom/domain/repository/UserRoomRepository.java
Labels: 현준, ⚡️ fix, 🍀 refactor

#189 [TEST] Auth 도메인 관련 테스트 코드 작성
  src/main/java/com/example/bookjourneybackend/global/scheduler/BestsellerUpdateScheduler.java
  src/test/java/com/example/bookjourneybackend/domain/auth/service/AuthServiceTest.java
Labels: 희진, ⚠️ test

#197 [REFACTOR] 독서기록장에서 같이읽기에서 방 이름 반환
  src/main/java/com/example/bookjourneybackend/domain/room/dto/response/RecordInfo.java
  src/main/java/com/example/bookjourneybackend/domain/room/service/RoomArchiveService.java
Labels: 현준, ⚡️ fix, 🍀 refactor

#200 [TEST] Comment 도메인 테스트코드 작성
  src/main/java/com/example/bookjourneybackend/domain/comment/domain/dto/request/PostCommentRequest.java
  src/test/java/com/example/bookjourneybackend/domain/comment/service/CommentServiceTest.java
Labels: 나은, ⚠️ test

#201 [TEST] Room 도메인 관련 테스트 코드 작성
  src/main/java/com/example/bookjourneybackend/domain/room/dto/request/PostRoomCreateRequest.java
  src/main/java/com/example/bookjourneybackend/domain/userRoom/domain/UserRoom.java
  src/test/java/com/example/bookjourneybackend/domain/room/service/RoomArchiveServiceTest.java
  src/test/java/com/example/bookjourneybackend/domain/room/service/RoomServiceTest.java
Labels: 현준, ⚠️ test

#205 [TEST] 전체 엔티티 테스트 코드 작성
  src/main/java/com/example/bookjourneybackend/domain/room/service/RoomService.java
  src/main/java/com/example/bookjourneybackend/domain/userRoom/domain/repository/UserRoomRepository.java
  src/test/java/com/example/bookjourneybackend/domain/favorite/domain/repository/FavoriteRepositoryTest.java
  src/test/java/com/example/bookjourneybackend/domain/recentSearch/domain/repository/RecentSearchRepositoryTest.java
  src/test/java/com/example/bookjourneybackend/domain/room/domain/repository/RoomRepositoryTest.java
  src/test/java/com/example/bookjourneybackend/domain/user/domain/repository/UserRepositoryTest.java
  src/test/java/com/example/bookjourneybackend/domain/userRoom/domain/repository/UserRoomRepositoryTest.java
Labels: 현준, ⚠️ test
