Repository B00KJourney/bookJourney-backend, pull requests merged in 2025-01, with the labels that each got.

#10 [FEAT] Room 관련 엔티티 추가
  src/main/java/com/example/bookjourneybackend/domain/room/Room.java
  src/main/java/com/example/bookjourneybackend/domain/room/readTogether/Comment.java
  src/main/java/com/example/bookjourneybackend/domain/room/readTogether/CommentLike.java
  src/main/java/com/example/bookjourneybackend/domain/room/readTogether/Record.java
  src/main/java/com/example/bookjourneybackend/domain/room/readTogether/RecordLike.java
  src/main/java/com/example/bookjourneybackend/domain/room/readTogether/RoomTogether.java
  src/main/java/com/example/bookjourneybackend/global/entity/RoomType.java
  src/main/java/com/example/bookjourneybackend/global/entity/UserRole.java
  src/main/resources/application.yml
Labels: 희진, 🛠️ feat

#11 [FEAT] book 관련 entity 작성
  src/main/java/com/example/bookjourneybackend/domain/book/BestSeller.java
  src/main/java/com/example/bookjourneybackend/domain/book/Book.java
  src/main/java/com/example/bookjourneybackend/domain/book/BookImage.java
  src/main/java/com/example/bookjourneybackend/domain/book/Genre.java
  src/main/java/com/example/bookjourneybackend/global/entity/GenreType.java
Labels: 나은, 🛠️ feat

#12 [FEAT] User 관련 엔티티 작성
  compose.yaml
  src/main/java/com/example/bookjourneybackend/BookJourneyBackendApplication.java
  src/main/java/com/example/bookjourneybackend/domain/recentSearch/RecentSearch.java
  src/main/java/com/example/bookjourneybackend/domain/user/Favorite.java
  src/main/java/com/example/bookjourneybackend/domain/user/FavoriteGenre.java
  src/main/java/com/example/bookjourneybackend/domain/user/User.java
  src/main/java/com/example/bookjourneybackend/domain/user/UserImage.java
  src/main/resources/application.yml
Labels: 현준, 🛠️ feat

#21 [CHORE] cotroller advice 작성
  build.gradle
  src/main/java/com/example/bookjourneybackend/domain/record/domain/Record.java
  src/main/java/com/example/bookjourneybackend/domain/room/domain/Room.java
  src/main/java/com/example/bookjourneybackend/domain/test/TestController.java
  src/main/java/com/example/bookjourneybackend/global/common/exception/GlobalException.java
  src/main/java/com/example/bookjourneybackend/global/common/exception_handler/GlobalControllerAdvice.java
  src/main/java/com/example/bookjourneybackend/global/common/response/BaseErrorResponse.java
  src/main/java/com/example/bookjourneybackend/global/common/response/BaseResponse.java
  src/main/java/com/example/bookjourneybackend/global/common/response/status/BaseExceptionResponseStatus.java
  src/main/java/com/example/bookjourneybackend/global/common/response/status/ResponseStatus.java
  src/main/java/com/example/bookjourneybackend/global/handler/GlobalExceptionHandler.java
  src/main/java/com/example/bookjourneybackend/global/response/status/CommonErrorCode.java
  src/main/java/com/example/bookjourneybackend/global/response/status/UserErrorCode.java
Labels: 희진, 🧹 chore

#24 [REFACTOR] dto 유효성 검증용 핸들러 추가
  build.gradle
  src/main/java/com/example/bookjourneybackend/domain/test/TestController.java
  src/main/java/com/example/bookjourneybackend/domain/test/TestRequest.java
  src/main/java/com/example/bookjourneybackend/global/config/RedisConfig.java
  src/main/java/com/example/bookjourneybackend/global/exception/GlobalException.java
  src/main/java/com/example/bookjourneybackend/global/handler/GlobalControllerAdvice.java
  src/main/java/com/example/bookjourneybackend/global/response/BaseErrorResponse.java
  src/main/java/com/example/bookjourneybackend/global/response/BaseResponse.java
  src/main/java/com/example/bookjourneybackend/global/response/status/BaseExceptionResponseStatus.java
  src/main/java/com/example/bookjourneybackend/global/response/status/ResponseStatus.java
Labels: 현준, 🍀 refactor

#26 [FEAT] 로그인 기능 구현
  build.gradle
  src/main/java/com/example/bookjourneybackend/domain/auth/controller/AuthController.java
  src/main/java/com/example/bookjourneybackend/domain/auth/domain/dto/request/PostAuthLoginRequest.java
  src/main/java/com/example/bookjourneybackend/domain/auth/domain/dto/response/PostAuthLoginResponse.java
  src/main/java/com/example/bookjourneybackend/domain/auth/service/AuthService.java
  src/main/java/com/example/bookjourneybackend/domain/auth/service/TokenService.java
  src/main/java/com/example/bookjourneybackend/domain/user/domain/repository/UserRepository.java
  src/main/java/com/example/bookjourneybackend/global/config/PasswordEncoderConfig.java
  src/main/java/com/example/bookjourneybackend/global/config/RedisConfig.java
  src/main/java/com/example/bookjourneybackend/global/config/SecurityConfig.java
  src/main/java/com/example/bookjourneybackend/global/response/status/BaseExceptionResponseStatus.java
  src/main/java/com/example/bookjourneybackend/global/util/JwtAuthenticationFilter.java
  src/main/java/com/example/bookjourneybackend/global/util/JwtUtil.java
  src/main/resources/application.yml
Labels: 희진, 🛠️ feat

#27 [FEAT] 책 검색 책 목록 구현
  build.gradle
  src/main/java/com/example/bookjourneybackend/domain/book/controller/BookController.java
  src/main/java/com/example/bookjourneybackend/domain/book/domain/Book.java
  src/main/java/com/example/bookjourneybackend/domain/book/domain/GenreType.java
  src/main/java/com/example/bookjourneybackend/domain/book/domain/repository/BookRepository.java
  src/main/java/com/example/bookjourneybackend/domain/book/dto/request/GetBookListRequest.java
  src/main/java/com/example/bookjourneybackend/domain/book/dto/response/BookInfo.java
  src/main/java/com/example/bookjourneybackend/domain/book/dto/response/GetBookListResponse.java
  src/main/java/com/example/bookjourneybackend/domain/book/service/BookCacheService.java
  src/main/java/com/example/bookjourneybackend/domain/book/service/BookService.java
  src/main/java/com/example/bookjourneybackend/global/config/AppConfig.java
  src/main/java/com/example/bookjourneybackend/global/config/RedisCacheConfig.java
  src/main/java/com/example/bookjourneybackend/global/config/RedisConfig.java
  src/main/java/com/example/bookjourneybackend/global/config/SecurityConfig.java
  src/main/java/com/example/bookjourneybackend/global/config/WebConfig.java
  src/main/java/com/example/bookjourneybackend/global/resolver/GetBookListRequestArgumentResolver.java
  src/main/java/com/example/bookjourneybackend/global/response/status/BaseExceptionResponseStatus.java
  src/main/resources/application.yml
Labels: 현준, 🛠️ feat

#34 [FEAT] 책 정보 상세보기 구현
  src/main/java/com/example/bookjourneybackend/domain/book/controller/BookController.java
  src/main/java/com/example/bookjourneybackend/domain/book/domain/Book.java
  src/main/java/com/example/bookjourneybackend/domain/book/domain/repository/BookRepository.java
  src/main/java/com/example/bookjourneybackend/domain/book/dto/response/BookInfo.java
  src/main/java/com/example/bookjourneybackend/domain/book/dto/response/GetBookInfoResponse.java
  src/main/java/com/example/bookjourneybackend/domain/book/service/BookCacheService.java
  src/main/java/com/example/bookjourneybackend/domain/book/service/BookService.java
  src/main/java/com/example/bookjourneybackend/domain/favorite/domain/repository/FavoriteRepository.java
  src/main/java/com/example/bookjourneybackend/global/config/RedisCacheConfig.java
  src/main/java/com/example/bookjourneybackend/global/config/SecurityConfig.java
  src/main/java/com/example/bookjourneybackend/global/util/AladinApiUtil.java
Labels: 현준, 🛠️ feat

#38 [REFACTOR] room 관련 entity 수정에 따른 변경사항 반영
  src/main/java/com/example/bookjourneybackend/domain/readAlone/ReadAlone.java
  src/main/java/com/example/bookjourneybackend/domain/readTogether/controller/ReadTogetherController.java
  src/main/java/com/example/bookjourneybackend/domain/readTogether/domain/ReadTogether.java
  src/main/java/com/example/bookjourneybackend/domain/readTogether/domain/repository/ReadTogetherRepository.java
  src/main/java/com/example/bookjourneybackend/domain/readTogether/dto/response/GetRoomInfoResponse.java
  src/main/java/com/example/bookjourneybackend/domain/readTogether/dto/response/RoomData.java
  src/main/java/com/example/bookjourneybackend/domain/readTogether/service/ReadTogetherService.java
  src/main/java/com/example/bookjourneybackend/domain/record/domain/Record.java
  src/main/java/com/example/bookjourneybackend/domain/room/controller/RoomController.java
  src/main/java/com/example/bookjourneybackend/domain/room/domain/Room.java
  src/main/java/com/example/bookjourneybackend/domain/room/domain/repository/RoomRepository.java
  src/main/java/com/example/bookjourneybackend/domain/room/dto/response/GetRoomInfoResponse.java
  src/main/java/com/example/bookjourneybackend/domain/room/dto/response/RoomMemberInfo.java
  src/main/java/com/example/bookjourneybackend/domain/room/service/RoomService.java
  src/main/java/com/example/bookjourneybackend/domain/user/domain/User.java
  src/main/java/com/example/bookjourneybackend/domain/userRoom/controller/UserRoomController.java
  src/main/java/com/example/bookjourneybackend/domain/userRoom/domain/RoomType.java
  src/main/java/com/example/bookjourneybackend/domain/userRoom/domain/UserRole.java
  src/main/java/com/example/bookjourneybackend/domain/userRoom/domain/UserRoom.java
  src/main/java/com/example/bookjourneybackend/domain/userRoom/domain/repository/UserRoomRepository.java
  src/main/java/com/example/bookjourneybackend/domain/userRoom/service/UserRoomService.java
  src/main/java/com/example/bookjourneybackend/global/config/SecurityConfig.java
  src/main/java/com/example/bookjourneybackend/global/response/status/BaseExceptionResponseStatus.java
Labels: 나은, 🍀 refactor

#39 [REFACTOR] DB 구조 수정 및 양방향 연관관계 설정
  src/main/java/com/example/bookjourneybackend/domain/bestSeller/controller/BestSellerController.java
  src/main/java/com/example/bookjourneybackend/domain/bestSeller/domain/BestSeller.java
  src/main/java/com/example/bookjourneybackend/domain/bestSeller/domain/repository/BestSellerRepository.java
  src/main/java/com/example/bookjourneybackend/domain/bestSeller/service/BestSellerService.java
  src/main/java/com/example/bookjourneybackend/domain/book/domain/Book.java
  src/main/java/com/example/bookjourneybackend/domain/book/domain/BookImage.java
  src/main/java/com/example/bookjourneybackend/domain/book/domain/Genre.java
  src/main/java/com/example/bookjourneybackend/domain/comment/domain/Comment.java
  src/main/java/com/example/bookjourneybackend/domain/comment/domain/CommentLike.java
  src/main/java/com/example/bookjourneybackend/domain/favorite/domain/Favorite.java
  src/main/java/com/example/bookjourneybackend/domain/recentSearch/domain/RecentSearch.java
  src/main/java/com/example/bookjourneybackend/domain/record/domain/Record.java
  src/main/java/com/example/bookjourneybackend/domain/record/domain/RecordLike.java
  src/main/java/com/example/bookjourneybackend/domain/room/controller/RoomController.java
  src/main/java/com/example/bookjourneybackend/domain/room/domain/Room.java
  src/main/java/com/example/bookjourneybackend/domain/room/service/RoomService.java
  src/main/java/com/example/bookjourneybackend/domain/user/domain/FavoriteGenre.java
  src/main/java/com/example/bookjourneybackend/domain/user/domain/User.java
  src/main/java/com/example/bookjourneybackend/domain/userRoom/domain/UserRoom.java
Labels: 현준, ⚡️ fix, 🍀 refactor

#41 [REFACTOR] @LoginUserId 어노테이션 정의 및 적용
  src/main/java/com/example/bookjourneybackend/domain/book/controller/BookController.java
  src/main/java/com/example/bookjourneybackend/global/annotation/LoginUserId.java
  src/main/java/com/example/bookjourneybackend/global/config/WebConfig.java
  src/main/java/com/example/bookjourneybackend/global/resolver/LoginUserResolver.java
Labels: 현준, 🍀 refactor

#44 [FEAT] 책 목록 선택시 책 상세보기 구현
  src/main/java/com/example/bookjourneybackend/domain/room/controller/RoomController.java
  src/main/java/com/example/bookjourneybackend/domain/room/dto/response/GetRoomDetailResponse.java
  src/main/java/com/example/bookjourneybackend/domain/room/service/RoomService.java
Labels: 나은, 🛠️ feat

#46 [FEAT] 방 생성 api 구현
  src/main/java/com/example/bookjourneybackend/domain/book/controller/BookController.java
  src/main/java/com/example/bookjourneybackend/domain/book/domain/Book.java
  src/main/java/com/example/bookjourneybackend/domain/book/domain/GenreType.java
  src/main/java/com/example/bookjourneybackend/domain/book/dto/request/GetBookListRequest.java
  src/main/java/com/example/bookjourneybackend/domain/book/service/BookCacheService.java
  src/main/java/com/example/bookjourneybackend/domain/book/service/BookService.java
  src/main/java/com/example/bookjourneybackend/domain/room/controller/RoomController.java
  src/main/java/com/example/bookjourneybackend/domain/room/domain/Room.java
  src/main/java/com/example/bookjourneybackend/domain/room/domain/RoomType.java
  src/main/java/com/example/bookjourneybackend/domain/room/dto/request/PostRoomCreateRequest.java
  src/main/java/com/example/bookjourneybackend/domain/room/dto/response/PostRoomCreateResponse.java
  src/main/java/com/example/bookjourneybackend/domain/room/service/RoomService.java
  src/main/java/com/example/bookjourneybackend/domain/userRoom/domain/RoomType.java
  src/main/java/com/example/bookjourneybackend/domain/userRoom/domain/UserRoom.java
  src/main/java/com/example/bookjourneybackend/global/entity/BaseEntity.java
  src/main/java/com/example/bookjourneybackend/global/response/status/BaseExceptionResponseStatus.java
  src/main/java/com/example/bookjourneybackend/global/util/AladinApiUtil.java
Labels: 현준, 🛠️ feat

#48 [FEAT] 읽기횟수가 가장 많은 책 조회 구현
  src/main/java/com/example/bookjourneybackend/domain/book/controller/BookController.java
  src/main/java/com/example/bookjourneybackend/domain/book/domain/repository/BookRepository.java
  src/main/java/com/example/bookjourneybackend/domain/book/dto/response/GetBookPopularResponse.java
  src/main/java/com/example/bookjourneybackend/domain/book/service/BookService.java
  src/main/java/com/example/bookjourneybackend/global/response/status/BaseExceptionResponseStatus.java
Labels: 현준, 🛠️ feat

#49 [FEAT] 방 목록 방 검색 구현
  src/main/java/com/example/bookjourneybackend/domain/room/controller/RoomController.java
  src/main/java/com/example/bookjourneybackend/domain/room/domain/Room.java
  src/main/java/com/example/bookjourneybackend/domain/room/domain/SearchType.java
  src/main/java/com/example/bookjourneybackend/domain/room/domain/repository/RoomRepository.java
  src/main/java/com/example/bookjourneybackend/domain/room/dto/response/GetRoomInfoResponse.java
  src/main/java/com/example/bookjourneybackend/domain/room/dto/response/GetRoomSearchResponse.java
  src/main/java/com/example/bookjourneybackend/domain/room/dto/response/RoomInfo.java
  src/main/java/com/example/bookjourneybackend/domain/room/service/RoomService.java
  src/main/java/com/example/bookjourneybackend/global/response/status/BaseExceptionResponseStatus.java
Labels: 나은, 🛠️ feat, ⚡️ fix, 🍀 refactor

#51 [REFACTOR]: 책 찾기 api의 쿼리 파라미터에서 genre가 null로 넘어올 경우 예외처리
  src/main/java/com/example/bookjourneybackend/domain/book/dto/request/GetBookListRequest.java
  src/main/java/com/example/bookjourneybackend/global/resolver/GetBookListRequestArgumentResolver.java
  src/main/java/com/example/bookjourneybackend/global/response/status/BaseExceptionResponseStatus.java
  src/main/java/com/example/bookjourneybackend/global/util/AladinApiUtil.java
Labels: 현준, ⚡️ fix, 🍀 refactor

#56 [REFACTOR] 방 생성시 DB 존재여부 로직 수정
  src/main/java/com/example/bookjourneybackend/domain/book/domain/Book.java
  src/main/java/com/example/bookjourneybackend/domain/room/service/RoomService.java
Labels: 현준, ⚡️ fix, 🍀 refactor

#60 [FEAT]: 기록 작성
  src/main/java/com/example/bookjourneybackend/domain/record/controller/RecordController.java
  src/main/java/com/example/bookjourneybackend/domain/record/domain/Record.java
  src/main/java/com/example/bookjourneybackend/domain/record/domain/RecordType.java
  src/main/java/com/example/bookjourneybackend/domain/record/dto/request/PostRecordRequest.java
  src/main/java/com/example/bookjourneybackend/domain/record/dto/response/PostRecordResponse.java
  src/main/java/com/example/bookjourneybackend/domain/record/service/RecordService.java
  src/main/java/com/example/bookjourneybackend/global/response/status/BaseExceptionResponseStatus.java
Labels: 나은, 🛠️ feat, 🍀 refactor

#61 [REFACTOR] 책 찾기 api 수정
  src/main/java/com/example/bookjourneybackend/domain/book/dto/request/GetBookListRequest.java
  src/main/java/com/example/bookjourneybackend/global/resolver/GetBookListRequestArgumentResolver.java
  src/main/java/com/example/bookjourneybackend/global/response/status/BaseExceptionResponseStatus.java
Labels: 현준, 🍀 refactor

#53 [FEAT] 엑세스 토큰 재발급 구현
  build.gradle
  src/main/java/com/example/bookjourneybackend/domain/auth/controller/AuthController.java
  src/main/java/com/example/bookjourneybackend/domain/auth/domain/dto/request/PostAuthAccessTokenReissueRequest.java
  src/main/java/com/example/bookjourneybackend/domain/auth/domain/dto/request/PostAuthLoginRequest.java
  src/main/java/com/example/bookjourneybackend/domain/auth/domain/dto/response/PostAuthAccessTokenReissueResponse.java
  src/main/java/com/example/bookjourneybackend/domain/auth/service/AuthService.java
  src/main/java/com/example/bookjourneybackend/domain/book/controller/BookController.java
  src/main/java/com/example/bookjourneybackend/global/config/AppConfig.java
  src/main/java/com/example/bookjourneybackend/global/config/JwtAuthenticationEntryPoint.java
  src/main/java/com/example/bookjourneybackend/global/config/SecurityConfig.java
  src/main/java/com/example/bookjourneybackend/global/handler/GlobalControllerAdvice.java
  src/main/java/com/example/bookjourneybackend/global/resolver/LoginUserResolver.java
  src/main/java/com/example/bookjourneybackend/global/response/BaseErrorResponse.java
  src/main/java/com/example/bookjourneybackend/global/response/status/BaseExceptionResponseStatus.java
  src/main/java/com/example/bookjourneybackend/global/util/HttpHeader.java
  src/main/java/com/example/bookjourneybackend/global/util/JwtAuthenticationFilter.java
  src/main/java/com/example/bookjourneybackend/global/util/JwtUtil.java
  src/main/resources/application.yml
Labels: 희진, 🛠️ feat, ⚡️ fix, 🍀 refactor

#65 [FEAT] 로그아웃 기능 구현
  src/main/java/com/example/bookjourneybackend/domain/auth/controller/AuthController.java
  src/main/java/com/example/bookjourneybackend/domain/auth/service/AuthService.java
  src/main/java/com/example/bookjourneybackend/domain/user/domain/repository/UserRepository.java
Labels: 희진, 🛠️ feat

#67 [FEAT] 진행 중인 기록 조회 구현
  src/main/java/com/example/bookjourneybackend/domain/book/domain/Book.java
  src/main/java/com/example/bookjourneybackend/domain/room/controller/RoomController.java
  src/main/java/com/example/bookjourneybackend/domain/room/domain/SearchType.java
  src/main/java/com/example/bookjourneybackend/domain/room/domain/SortType.java
  src/main/java/com/example/bookjourneybackend/domain/room/dto/request/PostRoomCreateRequest.java
  src/main/java/com/example/bookjourneybackend/domain/room/dto/response/GetRoomActiveResponse.java
  src/main/java/com/example/bookjourneybackend/domain/room/dto/response/RecordInfo.java
  src/main/java/com/example/bookjourneybackend/domain/room/service/RoomService.java
  src/main/java/com/example/bookjourneybackend/domain/userRoom/domain/repository/UserRoomRepository.java
  src/main/java/com/example/bookjourneybackend/global/config/initData/BookInitializer.java
  src/main/java/com/example/bookjourneybackend/global/config/initData/UserRoomInitializer.java
  src/main/java/com/example/bookjourneybackend/global/handler/GlobalControllerAdvice.java
  src/main/java/com/example/bookjourneybackend/global/response/status/BaseExceptionResponseStatus.java
Labels: 현준, 🛠️ feat

#69 [FEAT] 진행 중인 기록 삭제 구현
  src/main/java/com/example/bookjourneybackend/domain/record/service/RecordService.java
  src/main/java/com/example/bookjourneybackend/domain/room/controller/RoomController.java
  src/main/java/com/example/bookjourneybackend/domain/room/service/RoomService.java
  src/main/java/com/example/bookjourneybackend/domain/userRoom/domain/repository/UserRoomRepository.java
  src/main/java/com/example/bookjourneybackend/global/entity/BaseEntity.java
  src/main/java/com/example/bookjourneybackend/global/response/status/BaseExceptionResponseStatus.java
Labels: 현준, 🛠️ feat

#72 [REFACTOR] room 관련 수정
  src/main/java/com/example/bookjourneybackend/domain/record/service/RecordService.java
  src/main/java/com/example/bookjourneybackend/domain/room/dto/request/PostRoomCreateRequest.java
  src/main/java/com/example/bookjourneybackend/domain/room/service/RoomService.java
  src/main/java/com/example/bookjourneybackend/domain/userRoom/domain/UserRoom.java
  src/main/java/com/example/bookjourneybackend/domain/userRoom/domain/repository/UserRoomRepository.java
  src/main/java/com/example/bookjourneybackend/global/config/initData/UserRoomInitializer.java
  src/main/java/com/example/bookjourneybackend/global/response/status/BaseExceptionResponseStatus.java
  src/main/resources/application.yml
Labels: 나은, ⚡️ fix, 🍀 refactor

#73 [FEAT] 전체 기록 조회
  src/main/java/com/example/bookjourneybackend/domain/record/controller/RecordController.java
  src/main/java/com/example/bookjourneybackend/domain/record/domain/RecordSortType.java
  src/main/java/com/example/bookjourneybackend/domain/record/domain/repository/RecordLikeRepository.java
  src/main/java/com/example/bookjourneybackend/domain/record/domain/repository/RecordRepository.java
  src/main/java/com/example/bookjourneybackend/domain/record/dto/response/GetEntireRecordResponse.java
  src/main/java/com/example/bookjourneybackend/domain/record/dto/response/RecordInfo.java
  src/main/java/com/example/bookjourneybackend/domain/record/service/RecordService.java
  src/main/java/com/example/bookjourneybackend/domain/room/service/RoomService.java
  src/main/java/com/example/bookjourneybackend/global/response/status/BaseExceptionResponseStatus.java
  src/main/java/com/example/bookjourneybackend/global/util/DateUtil.java
Labels: 나은, 🛠️ feat, ⚡️ fix, 🍀 refactor

#74 [FEAT] 사용자별 베스트셀러 조회, 베스트셀러 리스트 api 요청 및 DB에 저장
  src/main/java/com/example/bookjourneybackend/BookJourneyBackendApplication.java
  src/main/java/com/example/bookjourneybackend/domain/book/controller/BookController.java
  src/main/java/com/example/bookjourneybackend/domain/book/domain/Book.java
  src/main/java/com/example/bookjourneybackend/domain/book/domain/GenreType.java
  src/main/java/com/example/bookjourneybackend/domain/book/domain/repository/BookRepository.java
  src/main/java/com/example/bookjourneybackend/domain/book/dto/response/BestSellerImageUrl.java
  src/main/java/com/example/bookjourneybackend/domain/book/dto/response/GetBookBestSellersResponse.java
  src/main/java/com/example/bookjourneybackend/domain/book/service/BestSellerService.java
  src/main/java/com/example/bookjourneybackend/domain/book/service/BestsellerUpdateScheduler.java
  src/main/java/com/example/bookjourneybackend/domain/book/service/BookCacheService.java
  src/main/java/com/example/bookjourneybackend/domain/book/service/BookService.java
  src/main/java/com/example/bookjourneybackend/domain/room/service/RoomService.java
  src/main/java/com/example/bookjourneybackend/domain/user/domain/FavoriteGenre.java
  src/main/java/com/example/bookjourneybackend/domain/user/domain/repository/FavoriteGenreRepository.java
  src/main/java/com/example/bookjourneybackend/global/config/initData/BookInitializer.java
  src/main/java/com/example/bookjourneybackend/global/config/initData/DataLoader.java
  src/main/java/com/example/bookjourneybackend/global/config/initData/FavoriteGenreInitializer.java
  src/main/java/com/example/bookjourneybackend/global/response/status/BaseExceptionResponseStatus.java
  src/main/java/com/example/bookjourneybackend/global/util/AladinApiUtil.java
Labels: 희진, 🛠️ feat, ⚡️ fix, 🍀 refactor

#76 [FEAT] 페이지 별 기록 조회
  src/main/java/com/example/bookjourneybackend/domain/record/controller/RecordController.java
  src/main/java/com/example/bookjourneybackend/domain/record/domain/RecordSortType.java
  src/main/java/com/example/bookjourneybackend/domain/record/domain/repository/RecordLikeRepository.java
  src/main/java/com/example/bookjourneybackend/domain/record/domain/repository/RecordRepository.java
  src/main/java/com/example/bookjourneybackend/domain/record/dto/response/GetRecordResponse.java
  src/main/java/com/example/bookjourneybackend/domain/record/dto/response/RecordInfo.java
  src/main/java/com/example/bookjourneybackend/domain/record/service/RecordService.java
  src/main/java/com/example/bookjourneybackend/global/response/status/BaseExceptionResponseStatus.java
Labels: 나은, 🛠️ feat, 🍀 refactor

#89 [REFACTOR]: 더미데이터 비밀번호 인코딩
  src/main/java/com/example/bookjourneybackend/global/config/initData/UserInitializer.java
Labels: 희진, 🍀 refactor

#78 [FEAT] 방 참여하기
  src/main/java/com/example/bookjourneybackend/domain/record/domain/RecordType.java
  src/main/java/com/example/bookjourneybackend/domain/record/service/RecordService.java
  src/main/java/com/example/bookjourneybackend/domain/room/controller/RoomController.java
  src/main/java/com/example/bookjourneybackend/domain/room/dto/request/PostRoomCreateRequest.java
  src/main/java/com/example/bookjourneybackend/domain/room/dto/response/GetRoomDetailResponse.java
  src/main/java/com/example/bookjourneybackend/domain/room/dto/response/GetRoomInfoResponse.java
  src/main/java/com/example/bookjourneybackend/domain/room/dto/response/PostJoinRoomResponse.java
  src/main/java/com/example/bookjourneybackend/domain/room/service/RoomService.java
  src/main/java/com/example/bookjourneybackend/domain/userRoom/domain/UserRoom.java
  src/main/java/com/example/bookjourneybackend/domain/userRoom/domain/repository/UserRoomRepository.java
  src/main/java/com/example/bookjourneybackend/global/config/initData/UserRoomInitializer.java
  src/main/java/com/example/bookjourneybackend/global/response/status/BaseExceptionResponseStatus.java
Labels: 나은, 🛠️ feat, ⚡️ fix

#82 [FEAT] 닉네임 중복 검증 구현
  src/main/java/com/example/bookjourneybackend/domain/user/controller/UserController.java
  src/main/java/com/example/bookjourneybackend/domain/user/domain/dto/request/PostUsersNicknameValidationRequest.java
  src/main/java/com/example/bookjourneybackend/domain/user/domain/dto/response/PostUsersNicknameValidationResponse.java
  src/main/java/com/example/bookjourneybackend/domain/user/domain/repository/UserRepository.java
  src/main/java/com/example/bookjourneybackend/domain/user/service/UserService.java
Labels: 희진, 🛠️ feat

#90 [FEAT] 방 나가기
  src/main/java/com/example/bookjourneybackend/domain/record/domain/repository/RecordRepository.java
  src/main/java/com/example/bookjourneybackend/domain/room/controller/RoomController.java
  src/main/java/com/example/bookjourneybackend/domain/room/service/RoomService.java
  src/main/java/com/example/bookjourneybackend/domain/user/service/UserService.java
  src/main/java/com/example/bookjourneybackend/global/response/status/BaseExceptionResponseStatus.java
Labels: 현준, 🛠️ feat
